#= require_tree ./app/adapters
#= require_tree ./app/mixins
#= require_tree ./app/models
#= require_tree ./app/controllers
#= require_tree ./app/views
#= require_tree ./app/helpers
#= require_tree ./app/components
#= require_tree ./app/templates
#= require ./app/router
#= require_self
